
server:
  port: 8880
spring:
  datasource:
    url: jdbc:mysql://47.108.210.238:3306/survey?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1yan!YAN
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  #\u6253\u5370sql\u5230\u63A7\u5236\u53F0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true    #开启驼峰命名